services:
  db:
    image: postgres:16-alpine
    container_name: super_auth-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretkey
      - POSTGRES_DB=super_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app

  redis:
    image: redis:7-alpine
    container_name: super_auth-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app

volumes:
  postgres_data:
  redis_data:

networks:
  app:
